name: build as C++ for S2E

on:
  pull_request:
    paths:
      - 'c2a_core_main.c'
      - 'c2a_core_main.h'
      - 'Applications/**'
      - 'CmdTlm/**'
      - 'Drivers/**'
      - 'IfWrapper/**'
      - 'System/**'
      - 'Examples/minimum_user_for_s2e/CMakeLists.txt'
      - 'Examples/minimum_user_for_s2e/src/**'
      - 'setup.bat'
      - 'setup.sh'

jobs:
  build_minimum_user_as_cxx:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup
        shell: cmd
        run: .\setup.bat

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e
        run: |
          mkdir build
          cd build
          cmake .. -A Win32

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cmake --build .
