name: build as C++ for S2E

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build_minimum_user_as_cxx:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        shell: cmd
        run: ./setup.bat

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e
        run: |
          mkdir build
          cd build
          cmake .. -A Win32

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cmake --build .

  build_s2e_mockup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        shell: cmd
        run: ./setup.bat

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e/src/s2e_mockup
        run: |
          mkdir build
          cd build
          cmake .. -A Win32

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/src/s2e_mockup/build
        run: cmake --build .
