name: build as C89 using SILS Mockup with Wextra

on:
  pull_request:
    paths:
      - 'c2a_core_main.c'
      - 'c2a_core_main.h'
      - 'Applications/**'
      - 'CmdTlm/**'
      - 'Drivers/**'
      - 'IfWrapper/**'
      - 'System/**'
      - 'Examples/minimum_user_for_s2e/CMakeLists.txt'
      - 'Examples/minimum_user_for_s2e/src/**'
      - 'setup.bat'
      - 'setup.sh'

jobs:
  build_minimum_user_as_c89_with_wextra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt-get install -y libc6-dev-i386

      - name: setup
        shell: bash
        run: ./setup.sh

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_SILS_MOCKUP=ON -DCMAKE_CXX_FLAGS="-Wextra"

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cmake --build .
