name: build as C89 using SILS Mockup

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '.github/workflows/build_as_c89.yml'
      - 'c2a_core_main.c'
      - 'c2a_core_main.h'
      - 'common.cmake'
      - 'Applications/**'
      - 'CmdTlm/**'
      - 'Drivers/**'
      - 'IfWrapper/**'
      - 'Library/**'
      - 'System/**'
      - 'Examples/minimum_user_for_s2e/CMakeLists.txt'
      - 'Examples/minimum_user_for_s2e/src/**'
      - 'setup.bat'
      - 'setup.sh'

jobs:
  gen_build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: generate matrix json
        id: gen-matrix
        shell: bash
        run: |
          compiler=(
            "gcc"
            "clang"
          )
          warning=(
          "Werror"
          "Wextra"
          )
          echo "[" > tmp
          for c in "${compiler[@]}"; do
            for w in "${warning[@]}"; do
              if [ "$c" == "gcc" ] && [ "$w" == "Werror" ]; then
                continue
              fi
              echo "{ \"compiler\": \"${c}\", \"warning\": \"${w}\" }" >> tmp
              echo "," >> tmp
            done
          done
          sed -i -e '$d' tmp # remove final comma
          echo "]" >> tmp
          sed -i -z 's/\n//g' tmp # remove newline
          jq < tmp
          echo "::set-output name=matrix::{\"include\": $(cat tmp) }"

  build_minimum_user_as_c89:
    runs-on: ubuntu-latest
    needs: gen_build_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.gen_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt-get install -y libc6-dev-i386 nkf

      - name: convert Shift-JIS to UTF-8
        if: matrix.compiler == 'clang'
        run: find -- . -type f \( -name '*.h' -or -name '*.c' \) -exec nkf --overwrite -S -w80 "{}" \;

      - name: setup
        shell: bash
        run: ./setup.sh

      - name: generate compile option
        id: compile_flags
        shell: bash
        run: |
          WERROR="OFF"
          WEXTRA="OFF"
          if ${{ contains(matrix.warning, 'Werror') }}; then
            WERROR="ON"
          fi
          if ${{ contains(matrix.warning, 'Wextra') }}; then
            WEXTRA="ON"
          fi
          echo "::set-output name=WERROR::${WERROR}"
          echo "::set-output name=WEXTRA::${WEXTRA}"

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e
        env:
          CC: ${{ matrix.compiler }}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DUSE_SILS_MOCKUP=ON -DADD_WERROR_FLAGS=${{ steps.compile_flags.outputs.WERROR }} -DADD_WEXTRA_FLAGS=${{ steps.compile_flags.outputs.WEXTRA }}

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cmake --build .

      - name: run
        working-directory: ./Examples/minimum_user_for_s2e/build
        shell: bash
        run: timeout 3 ./C2A || exit 0


      - name: install reviewdog
        if: matrix.compiler == 'clang' && matrix.warning == 'Wextra'
        uses: reviewdog/action-setup@v1.0.3

      - name: install clang-tidy
        if: matrix.compiler == 'clang' && matrix.warning == 'Wextra'
        run: sudo apt-get install -y clang-tidy-11

      - name: clang-tidy
        if: matrix.compiler == 'clang' && matrix.warning == 'Wextra'
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: |
          run-clang-tidy-11 > clang_tidy.log

      - name: clang-tidy result
        if: matrix.compiler == 'clang' && matrix.warning == 'Wextra'
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cat clang_tidy.log

      - name: reviewdog clang-tidy
        if: matrix.compiler == 'clang' && matrix.warning == 'Wextra'
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: |
          reviewdog -efm="%f:%l:%c: %tarning: %m" -diff="git diff FETCH_HEAD" -reporter=github-pr-check -name 'clang-tidy' -level warning < clang_tidy.log
