name: build as C89 using SILS Mockup

on:
  pull_request:
    paths:
      - '.github/workflows/build_as_c89.yml'
      - 'c2a_core_main.c'
      - 'c2a_core_main.h'
      - 'Applications/**'
      - 'CmdTlm/**'
      - 'Drivers/**'
      - 'IfWrapper/**'
      - 'System/**'
      - 'Examples/minimum_user_for_s2e/CMakeLists.txt'
      - 'Examples/minimum_user_for_s2e/src/**'
      - 'setup.bat'
      - 'setup.sh'

jobs:
  build_minimum_user_as_c89:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        warning: [Werror, Wextra]

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt-get install -y libc6-dev-i386

      - name: setup
        shell: bash
        run: ./setup.sh

      - name: generate compile option
        id: compile_flags
        shell: bash
        run: |
          WERROR="OFF"
          WEXTRA="OFF"
          if ${{ contains(matrix.warning, 'Werror') }}; then
            WERROR="ON"
          fi
          if ${{ contains(matrix.warning, 'Wextra') }}; then
            WEXTRA="ON"
          fi
          echo "::set-output name=WERROR::${WERROR}"
          echo "::set-output name=WEXTRA::${WEXTRA}"

      - name: cmake
        working-directory: ./Examples/minimum_user_for_s2e
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_SILS_MOCKUP=ON -DADD_WERROR_FLAGS=${{ steps.compile_flags.outputs.WERROR }} -DADD_WEXTRA_FLAGS=${{ steps.outputs.compile_flags.WEXTRA }}

      - name: build
        working-directory: ./Examples/minimum_user_for_s2e/build
        run: cmake --build .

      - name: run
        working-directory: ./Examples/minimum_user_for_s2e/build
        shell: bash
        run: timeout 3 ./C2A || exit 0
