name: check_encoding

on:
  push:

jobs:
  check_encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install chardet
      - name: check_encoding
          run: python check_encoding.py
          working-directory: ./Script/CI
